### ISSUE TITLE
addFilesFromDir() imports only the first line of each file

### ISSUE THREAD

**Issue by jalvesaq** [Ronggui/RQDA#12]
When I run `addFilesFromDir("/path/to/txt_files")` I get the warning:

> There were 50 or more warnings (use warnings() to see the first 50)

The warnings are all the same:

> In if (Encoding(content) != "UTF-8") { ... :
>  the condition has length > 1 and only the first element will be used

And only the first line of each file is imported.

I successfully imported the files with the commands:

```
setwd("/path/to/txt_files")
Files <- dir()
for(f in Files) RQDA:::ImportFile(f)
RQDA:::FileNamesUpdate()
```

I am using R 3.3.2 on Linux (Ubuntu 16.10).

**Comment by Ronggui** [comment]
it is fixed now.

**Comment by cownr10r** [comment]
This is not yet fixed. I'm still having problems. When I upload with the following code, I get NA populating the document window. 

R> setwd("/path/to/txt_files")
R> Files <- dir()
R> for(f in Files) RQDA:::ImportFile(f)
R> RQDA:::FileNamesUpdate()

I've also tried:

R> addFilesFromDir(dir, pattern = "*.txt$")

But this only imports names file names. I've downloaded the latest changes in RQDA from

https://github.com/Ronggui/RQDA

and I'm on a Mac, and finally, i'm using R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"

Please help. Thanks!

**Comment by cownr10r** [comment]
Dear Ronggui,

RQDA is working well right now. Thank you very much!

Mario
