### ISSUE TITLE
fail to write to database again, how to install RSQ Lite 1.0.0 on R version 3.2.3 ?

### ISSUE THREAD

**Issue by Therru1** [Ronggui/RQDA#14]
hello, 
I have R version 3.2.3, rqda version 0.2-8 and RSQLite 1.1-2.

each time I want to mark some text with rqda, it says "fail to write to database". 
here : https://github.com/Ronggui/RQDA/wiki/Note-on-%22Fail-to-write-to-database%22-%7C-RQDA,
I read that I had to install RSQ Lite 1.0.0.

so I tried,
but then I got this answer on the rstudio console  : 
> install.packages("Archive/RSQLite/RSQLite_1.0.0.tar.gz")
Installing package into ‘/home/veronique/R/x86_64-pc-linux-gnu-library/3.2’
(as ‘lib’ is unspecified)
Warning in install.packages :
package ‘Archive/RSQLite/RSQLite_1.0.0.tar.gz’ is not available (for R version 3.2.3, on the r console. 

could you please help me ? Thanks a lot :)

**Comment by jalvesaq** [comment]
@Ronggui Could you please submit the current development version of RQDA to CRAN? RSQLite requires compilation to be installed from source, and this will be difficult for some people. I am sure that many RQDA users know nothing about programming languages and those using Windows will not know that they should install Rtools to be able to compile RSQLite. Moreover, users might not find RQDA wiki on github and, thus, they would not guess that RSQLite should be downgraded.

**Comment by Chris-JAC** [comment]
Hi, Thanks for the RQDA - it looks a really viable option for my postgrad research.

I'm using RQDA 0.2-8, and was RSQLite 1.1-2 but trying to install RSQLite 1.0 without success.

I have this same issue with the codes and the 'fail to write to database'.  I suspect I have the problem that jalvesaq describes.  I'm using Windows so it seems that the normal installer picks a .zip version.  I've found one in the cran repository for version 3.0 or 3.1 but I can't work out how to force the process to install it.
(https://cran.r-project.org/bin/windows/contrib/3.0/RSQLite_1.0.0.zip)
My attempted command is:
install.packages("RSQLite",,repos = "https://cran.r-project.org/bin/windows/contrib/3.0/RSQLite_1.0.0.zip")

* Can someone provide me with the correct syntax?

In addition, I notice that when I do manage to get the code added to the file, (even though it says it is not writing to the database), often it isn't in the right place.  I suspect there is some error in calculating the text position when there are multiple labels.

**Comment by jalvesaq** [comment]
You may try this:
```r
update.packages()        # Answer "y" for everything
install.packages("RQDA") # Install RQDA's dependencies
# Now, update RQDA using the development version:
download.file("https://github.com/Ronggui/RQDA/archive/master.zip", "RQDA_master.zip")
unzip("RQDA_master.zip")
install.packages("RQDA-master", repos = NULL, type = "source",
                 INSTALL_opts = "--no-test-load")
```

**Comment by Chris-JAC** [comment]
Thanks - so that is the 'development' version which works with the newer
RSQLite.
That will be 'next step' for me if I have more troubles.  Working for now.

**Comment by Therru1** [comment]
thank you very much, it works.
I must say, that I had to do it on the Terminal and not in the R-console.
have a nice week :)

**Comment by jefische** [comment]
I was having this same issue a couple of months ago and gave up.  I recently attempted using RQDA again and now the "Failed to write to database" issue isn't popping up.  I'm using Rstudio with R version 3.3.2 RQDA version 0.3-0 and have RSQLite version 1.1-2.  Is the RQDA version I'm using the developer one?

**Comment by jalvesaq** [comment]
The last released version at https://cran.r-project.org/web/packages/RQDA/ is is 0.2-8. So, it looks like that your are using the development version which, however, also has issues. Please, see https://github.com/Ronggui/RQDA/issues/14

**Comment by jalvesaq** [comment]
@jefische The issue is #15 (I edited my last comment).

**Comment by Ronggui** [comment]
I have released a new version to CRAN, which should solve this problem.
Please Install the latest version from CRAN (instruction for Mac users can be found on  https://github.com/Ronggui/RQDA).

**Comment by pdcarvalho** [comment]
Hi, I can see you closed this topic but I am still getting this message and was not able to fix it. Previous experience for installing RQDA were easy and I am not an advanced user

Using R version 3.2.5 (2016-04-14) --
The RQDA Version - 0.2-8 2014

I tried to install RQDA
had some error messages and this message - Error : package 'RSQLite' 1.1.2 was found, but >= 2.0 is required by 'RQDA'

So I tried to install RSQLite and then went back to RQDA.
But the message was the same.

Then if I lauch RQDA it opens but appears to be the same 0.2-8 2016 Version

And I keep getting the message Unable to Write Database.

Here is a copy of the R screen

> install.packages("RQDA",dependencies=c("Depends", "Imports"))
Installing package into ‘C:/Users/PDC/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
also installing the dependency ‘RSQLite’


  There are binary versions available but the source versions are later:
        binary source needs_compilation
RSQLite  1.1-2    2.0              TRUE
RQDA     0.2-8  0.3-0             FALSE

  Binaries will be installed
tentando a URL 'https://cran.mtu.edu/bin/windows/contrib/3.2/RSQLite_1.1-2.zip'
Content type 'application/zip' length 1857914 bytes (1.8 MB)
downloaded 1.8 MB

package ‘RSQLite’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\PDC\AppData\Local\Temp\RtmpeWJUUg\downloaded_packages
installing the source package ‘RQDA’

tentando a URL 'https://cran.mtu.edu/src/contrib/RQDA_0.3-0.tar.gz'
Content type 'application/x-gzip' length 123773 bytes (120 KB)
downloaded 120 KB

* installing *source* package 'RQDA' ...
** package 'RQDA' successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
Error : package 'RSQLite' 1.1.2 was found, but >= 2.0 is required by 'RQDA'
ERROR: lazy loading failed for package 'RQDA'
* removing 'C:/Users/PDC/Documents/R/win-library/3.2/RQDA'
* restoring previous 'C:/Users/PDC/Documents/R/win-library/3.2/RQDA'

The downloaded source packages are in
        ‘C:\Users\PDC\AppData\Local\Temp\RtmpeWJUUg\downloaded_packages’
Warning messages:
1: execução do comando '"C:/PROGRA~1/R/R-32~1.5/bin/i386/R" CMD INSTALL -l "C:\Users\PDC\Documents\R\win-library\3.2" C:\Users\PDC\AppData\Local\Temp\RtmpeWJUUg/downloaded_packages/RQDA_0.3-0.tar.gz' teve status 1 
2: In install.packages("RQDA", dependencies = c("Depends", "Imports")) :
  installation of package ‘RQDA’ had non-zero exit status
> install.packages("RSQLite")
Installing package into ‘C:/Users/PDC/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is later:
        binary source needs_compilation
RSQLite  1.1-2    2.0              TRUE

  Binaries will be installed
tentando a URL 'https://cran.mtu.edu/bin/windows/contrib/3.2/RSQLite_1.1-2.zip'
Content type 'application/zip' length 1857914 bytes (1.8 MB)
downloaded 1.8 MB

package ‘RSQLite’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\PDC\AppData\Local\Temp\RtmpeWJUUg\downloaded_packages
> install.packages("RQDA",dependencies=c("Depends", "Imports"))
Installing package into ‘C:/Users/PDC/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
also installing the dependency ‘RSQLite’


  There are binary versions available but the source versions are later:
        binary source needs_compilation
RSQLite  1.1-2    2.0              TRUE
RQDA     0.2-8  0.3-0             FALSE

  Binaries will be installed
tentando a URL 'https://cran.mtu.edu/bin/windows/contrib/3.2/RSQLite_1.1-2.zip'
Content type 'application/zip' length 1857914 bytes (1.8 MB)
downloaded 1.8 MB

package ‘RSQLite’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\PDC\AppData\Local\Temp\RtmpeWJUUg\downloaded_packages
installing the source package ‘RQDA’

tentando a URL 'https://cran.mtu.edu/src/contrib/RQDA_0.3-0.tar.gz'
Content type 'application/x-gzip' length 123773 bytes (120 KB)
downloaded 120 KB

* installing *source* package 'RQDA' ...
** package 'RQDA' successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
Error : package 'RSQLite' 1.1.2 was found, but >= 2.0 is required by 'RQDA'
ERROR: lazy loading failed for package 'RQDA'
* removing 'C:/Users/PDC/Documents/R/win-library/3.2/RQDA'
* restoring previous 'C:/Users/PDC/Documents/R/win-library/3.2/RQDA'

The downloaded source packages are in
        ‘C:\Users\PDC\AppData\Local\Temp\RtmpeWJUUg\downloaded_packages’
Warning messages:
1: execução do comando '"C:/PROGRA~1/R/R-32~1.5/bin/i386/R" CMD INSTALL -l "C:\Users\PDC\Documents\R\win-library\3.2" C:\Users\PDC\AppData\Local\Temp\RtmpeWJUUg/downloaded_packages/RQDA_0.3-0.tar.gz' teve status 1 
2: In install.packages("RQDA", dependencies = c("Depends", "Imports")) :
  installation of package ‘RQDA’ had non-zero exit status
> library (RQDA)
Carregando pacotes exigidos: RSQLite
Carregando pacotes exigidos: gWidgetsRGtk2
Carregando pacotes exigidos: RGtk2
Carregando pacotes exigidos: gWidgets
Carregando pacotes exigidos: cairoDevice

Use 'RQDA()' to start the programme.

Warning: changing locked binding for ‘n’ in ‘gWidgets’ whilst loading ‘RQDA’
Error in Encoding(path) : vetor de caracteres esperado como argumento
[1] "C:\\Users\\PDC\\Desktop\\R abrir.txt"
[1] "C:\\Users\\PDC\\Desktop\\R abrir.txt"



I am really a beginner level user

Thanks

**Comment by Ronggui** [comment]
Please use a mirror which has the RSQLite 2.0.
